FROM openjdk:8-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
ARG CONFIG_REPO_URL
ARG CONFIG_GIT_USERNAME
ARG CONFIG_GIT_PASSWORD
ARG SPRING_ENV

ENV CONFIG_REPO_URL=$CONFIG_REPO_URL
ENV CONFIG_GIT_USERNAME=$CONFIG_GIT_USERNAME
ENV CONFIG_GIT_PASSWORD=$CONFIG_GIT_PASSWORD
ENV spring_profiles_active=$SPRING_ENV
EXPOSE 80
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/urandom", "-jar", "/app.jar"]
