server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:carolynrehm/assignforce-config-server.git
  application:
    name: config-service

info:
  component: config Server
  description: assignForce config Server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 